---
- name: Exerciese 1a
  hosts: arista:cisco:juniper
  gather_facts: false
  tasks:
    - eos_command:
        commands: "show ip arp"
      register: show_ip_arp_eos
      when: ansible_network_os == "eos"
      tags: eos
    - ios_command:
        commands: "show ip arp"
      register: show_ip_arp_ios
      when: ansible_network_os == "ios"
      tags: ios
    - junos_command:
        commands: "show arp"
      register: show_ip_arp_junos
      when: ansible_network_os == "junos"
      tags: junos
    - debug:
        var: show_ip_arp_eos['stdout_lines']
      when: ansible_network_os == "eos"
      tags: eos
 
